import type { MoM } from "./types";

export function momToMarkdown(mom: MoM): string {
  const info = mom.meeting_info;
  const out: string[] = [];

  out.push(`# ${info.title || "Meeting Minutes"}`);
  const metaBits = [info.date, info.duration, info.client_name].filter(Boolean);
  if (metaBits.length) out.push("", `**${metaBits.join(" · ")}**`);
  if (info.objective) out.push("", `_${info.objective}_`);

  if (info.participants?.length) {
    out.push("", "**Participants:** " + info.participants
      .map(p => p.role ? `${p.name} (${p.role})` : p.name).join(", "));
  }

  if (mom.executive_summary) {
    out.push("", "## Executive summary", "", mom.executive_summary);
  }

  if (mom.discussion_topics?.length) {
    out.push("", "## Topics discussed");
    for (const t of mom.discussion_topics) {
      out.push(`- **${t.title}** — ${t.summary}`);
    }
  }

  if (mom.decisions_log?.length) {
    out.push("", "## Decisions");
    for (const d of mom.decisions_log) {
      const bits: string[] = [`**${d.decision}**`];
      if (d.rationale) bits.push(`_${d.rationale}_`);
      if (d.owner) bits.push(`(Owner: ${d.owner})`);
      out.push(`- ${bits.join(" — ")}`);
    }
  }

  if (mom.action_items?.length) {
    out.push("", "## Action items", "",
      "| Action | Owner | Due | Priority | Status |",
      "| --- | --- | --- | --- | --- |");
    for (const a of mom.action_items) {
      const cells = [a.action, a.owner || "TBD", a.due_date || "TBD", a.priority, a.status]
        .map(c => String(c).replace(/\|/g, "\\|"));
      out.push(`| ${cells.join(" | ")} |`);
    }
  }

  if (mom.risks_issues?.length) {
    out.push("", "## Risks & issues");
    for (const r of mom.risks_issues) {
      const owner = r.owner ? ` (Owner: ${r.owner})` : "";
      out.push(`- **[${r.type} · ${r.impact}]** ${r.description}${owner}`);
    }
  }

  if (mom.timeline?.length) {
    out.push("", "## Timeline");
    for (const t of mom.timeline) {
      out.push(`- **${t.milestone}** — ${t.date}`);
    }
  }

  if (mom.open_questions?.length) {
    out.push("", "## Open questions");
    for (const q of mom.open_questions) {
      out.push(`- ${q}`);
    }
  }

  out.push("", "---", "_Strictly Private & Confidential · Deloitte · Generated by Teams-to-MoM_");
  return out.join("\n");
}
